"""Oracle fixtures for Prosodia's port of Sonora's device G2P.

Runs Sonora's training front end read-only and writes what the Rust port must
reproduce: unidecode's fold, op_g2p's normalized text per probe, every word
op_g2p sent to its neural graph with the IPA it got back, and the canonical
contraction tables (embedded by the Rust crate).

The fold is checked on every code point from U+0000 to U+10FFFF. unidecode is
GPL, so its output is not committed: `fold.json` holds an FNV-1a 64 hash per
4096 code points, over lines `XXXX=value\n`, and the code points it folds to
nothing are written as ranges to the Rust crate
(`device_g2p/fold/unidecode_empty.rs`). When a block fails, the Rust test
writes the fold's lines for it to a temp file; diff them against
`generate.py --dump LO HI` (hex), which prints unidecode's in the same format
and needs only unidecode.

Run from the Prosodia repo root on ai-lab-0:

    ../Sonora/github/.venv/bin/python crates/actor/tests/fixtures/device_g2p/generate.py
"""

import hashlib
import importlib.metadata
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[4]
SONORA = REPO.parent / "Sonora" / "github"
sys.path.insert(0, str(SONORA))
sys.path.insert(0, str(SONORA / "scripts" / "litert_export"))

import unidecode  # noqa: E402

FOLD_FIRST, FOLD_LAST, BLOCK = 0x0, 0x10FFFF, 0x1000
EMPTY_RS = REPO / "crates" / "actor" / "src" / "device_g2p" / "fold" / "unidecode_empty.rs"


def fold_code_points():
    """Every scalar value the fold is checked on: U+0000..U+10FFFF without surrogates."""
    return (cp for cp in range(FOLD_FIRST, FOLD_LAST + 1) if not 0xD800 <= cp <= 0xDFFF)


def fnv1a64(data):
    h = 0xCBF29CE484222325
    for b in data:
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def fold_fixture():
    """Per block of BLOCK code points, the FNV-1a 64 of `XXXX=value\n` for each
    code point in it; and the ranges unidecode folds to nothing."""
    lines, empty = {}, []
    for cp in fold_code_points():
        value = unidecode.unidecode(chr(cp))
        lines.setdefault(cp // BLOCK, []).append(f"{cp:04X}={value}\n")
        if not value:
            if empty and empty[-1][1] == cp - 1:
                empty[-1][1] = cp
            else:
                empty.append([cp, cp])
    hashes = {f"{b * BLOCK:04X}": f"{fnv1a64(''.join(ls).encode()):016x}" for b, ls in lines.items()}
    return hashes, empty


def write_empty_ranges(empty):
    rows = "".join(f"    (0x{lo:04X}, 0x{hi:04X}),\n" for lo, hi in empty)
    EMPTY_RS.write_text(
        "// Generated by crates/actor/tests/fixtures/device_g2p/generate.py; do not edit.\n"
        f"// unidecode {importlib.metadata.version('unidecode')}: the code points it folds to nothing.\n\n"
        "/// Inclusive, sorted, disjoint code-point ranges that unidecode folds to \"\".\n"
        f"pub(super) const UNIDECODE_EMPTY: &[(u32, u32)] = &[\n{rows}];\n"
    )


def sha256_file(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def write(path, obj):
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n")


def main():
    import device_g2p
    from matcha.text import op_g2p

    commit = subprocess.run(["git", "-C", str(SONORA), "rev-parse", "HEAD"],
                            capture_output=True, text=True, check=True).stdout.strip()
    dirty = subprocess.run(["git", "-C", str(SONORA), "status", "--porcelain", "--",
                            "matcha/text", "scripts/litert_export"],
                           capture_output=True, text=True, check=True).stdout.strip()
    if dirty:
        sys.exit(f"Sonora's front end has uncommitted changes:\n{dirty}")

    hashes, empty = fold_fixture()
    write(HERE / "fold.json", {"unidecode_version": importlib.metadata.version("unidecode"),
                               "sonora_commit": commit, "first": f"{FOLD_FIRST:04X}",
                               "last": f"{FOLD_LAST:04X}", "block": BLOCK, "fnv1a64": hashes})
    write_empty_ranges(empty)

    raw_tables = op_g2p.contraction_tables()
    canonical = json.dumps(raw_tables, ensure_ascii=False, indent=2, sort_keys=True)
    (REPO / "crates" / "actor" / "resources" / "g2p_contractions.json").write_text(canonical)
    tables = json.loads(canonical)
    probes = device_g2p.probe_sentences(tables)
    write(HERE / "normalize.json", {"sonora_commit": commit,
                                    "cases": [{"text": t, "normalized": op_g2p.normalize_for_tokens(t)}
                                              for t in probes]})

    host = op_g2p.OpenPhonemizerG2P(use_neural_oov=True, homographs=False)
    seen = {}
    neural_word = host._neural_word

    def recording(word):
        ipa = neural_word(word)
        seen[word] = ipa
        return ipa

    host._neural_word = recording
    for t in probes:
        host.phonemize(t)
    assets = Path(host.assets_dir)
    write(HERE / "neural.json", {"sonora_commit": commit,
                                 "sha256": {n: sha256_file(assets / n)
                                            for n in ("dp_g2p_matcha_fp16.tflite", "g2p_meta.json")},
                                 "contractions_sha256": hashlib.sha256(canonical.encode()).hexdigest(),
                                 "words": dict(sorted(seen.items()))})
    print(f"{len(hashes)} fold blocks, {len(empty)} empty ranges, {len(probes)} probes, {len(seen)} neural words, Sonora {commit[:9]}")


def dump(lo, hi):
    """unidecode's line for each code point in LO..HI, as the fold test hashes them."""
    sys.stdout.write("".join(f"{cp:04X}={unidecode.unidecode(chr(cp))}\n"
                             for cp in range(lo, hi + 1) if not 0xD800 <= cp <= 0xDFFF))


if __name__ == "__main__":
    if sys.argv[1:2] == ["--dump"]:
        if len(sys.argv) != 4:
            sys.exit("usage: generate.py --dump LO HI   (hex code points)")
        dump(int(sys.argv[2], 16), int(sys.argv[3], 16))
    else:
        main()
