import Foundation

#if canImport(MLX)
import MLX
#endif

/// Represents a style vector embedding generated by or loaded for the voice model.
public struct StyleVector: Sendable, Codable, Equatable {
    /// The raw floating-point array values of the style vector.
    public let data: [Float]
    /// The dimensions/shape of the style vector.
    public let shape: [Int]

    /// Initializes a new StyleVector instance.
    ///
    /// - Parameters:
    ///   - data: The raw floating-point data.
    ///   - shape: The shape dimensions.
    public init(data: [Float], shape: [Int]) {
        self.data = data
        self.shape = shape
    }
}

/// A target structure representing a single voice and its contribution fraction in a blend.
public struct CastingProfile: Sendable, Codable, Equatable {
    /// The name/identifier of the voice.
    public let voice: String
    /// The fractional mixing weight of this voice in the blend.
    public let fraction: Double

    /// Initializes a new CastingProfile target.
    ///
    /// - Parameters:
    ///   - voice: The voice name.
    ///   - fraction: The fraction weight (typically between 0.0 and 1.0).
    public init(voice: String, fraction: Double) {
        self.voice = voice
        self.fraction = fraction
    }
}

/// A thread-safe voice loader that handles loading, caching, downloading, and blending style vectors.
public final class VoiceLoader: Sendable {
    /// The directory URL where voice files are located.
    private let baseDirectory: URL
    /// In-memory cache of loaded voice style vectors with LRU eviction policy.
    private let cache = Locked<LRUCache<String, StyleVector>>(LRUCache(limit: 16))
    /// Optional downloader to retrieve missing voice packs from a remote server.
    public let downloader: VoiceDownloader?

    /// Initializes a new VoiceLoader instance.
    ///
    /// - Parameters:
    ///   - baseDirectory: The base directory URL to resolve voice files.
    ///   - downloader: An optional voice downloader.
    public init(baseDirectory: URL, downloader: VoiceDownloader? = nil) {
        self.baseDirectory = baseDirectory
        self.downloader = downloader
    }

    /// Clears the in-memory cache of loaded voice style vectors.
    public func clearCache() {
        cache.withLock { $0.removeAll() }
    }

    /// Load a voice pack by name, supporting both `.safetensors` and `.npy` formats.
    ///
    /// - Parameter voiceName: The name of the voice pack to load.
    /// - Returns: The loaded style vector.
    /// - Throws: An error if the file is missing or in an invalid format.
    public func loadVoice(named voiceName: String) throws -> StyleVector {
        if let cached = cache.withLock({ $0.get(voiceName) }) {
            return cached
        }

        // Try safetensors format first, then fallback to npy
        let safetensorsURL = baseDirectory.appendingPathComponent("\(voiceName).safetensors", isDirectory: false)
        let npyURL = baseDirectory.appendingPathComponent("\(voiceName).npy", isDirectory: false)

        var voicePack: StyleVector
        if FileManager.default.fileExists(atPath: safetensorsURL.path) {
            let arrays = try VoiceLoader.loadSafetensors(url: safetensorsURL)
            guard let firstArray = arrays.values.first else {
                throw StyleTTS2Error.missingVoice(voiceName)
            }
            voicePack = firstArray
        } else if FileManager.default.fileExists(atPath: npyURL.path) {
            #if canImport(MLX)
            let array = try loadArray(url: npyURL)
            let floats = array.asArray(Float.self)
            voicePack = StyleVector(data: floats, shape: array.shape)
            #else
            throw NSError(
                domain: "VoiceLoader",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "npy format requires MLX dependency to load."]
            )
            #endif
        } else {
            throw StyleTTS2Error.missingVoice(voiceName)
        }

        let normalizedPack: StyleVector
        switch voicePack.shape.count {
        case 2:
            normalizedPack = voicePack
        case 3 where voicePack.shape[1] == 1:
            // Squeezed axis 1: shape [d0, 1, d2] -> [d0, d2]
            let d0 = voicePack.shape[0]
            let d2 = voicePack.shape[2]
            normalizedPack = StyleVector(data: voicePack.data, shape: [d0, d2])
        default:
            throw StyleTTS2Error.expected2DVoicePack(voiceName, voicePack.shape)
        }

        cache.withLock { $0.set(normalizedPack, forKey: voiceName) }
        return normalizedPack
    }

    /// Creates a blended style array from multiple weighted voices.
    ///
    /// - Parameter blend: The list of weighted voice blends.
    /// - Returns: The combined style vector.
    /// - Throws: An error if loading any voice in the blend fails.
    public func loadCastingProfile(_ blend: CastingProfile) throws -> StyleVector {
        precondition(!blend.isEmpty, "Voice blend list must not be empty.")
        if blend.count == 1, let single = blend.first {
            return try loadVoice(named: single.voice)
        }

        var accumulator: [Float]?
        var totalFraction: Double = 0.0
        var shape: [Int] = []

        for target in blend {
            let pack = try loadVoice(named: target.voice)
            if shape.isEmpty {
                shape = pack.shape
                accumulator = [Float](repeating: 0.0, count: pack.data.count)
            } else {
                precondition(pack.shape == shape, "Voice shapes in blend must match.")
            }
            
            let weight = Float(target.fraction)
            for i in 0..<pack.data.count {
                accumulator![i] += pack.data[i] * weight
            }
            totalFraction += target.fraction
        }

        guard let blended = accumulator, totalFraction > 0.0 else {
            throw StyleTTS2Error.missingVoice(blend.first?.voice ?? "(none)")
        }

        let finalFraction = Float(totalFraction)
        let normalized = blended.map { $0 / finalFraction }
        return StyleVector(data: normalized, shape: shape)
    }

    /// Extracts the style embedding vector for a given phoneme count from a voice blend.
    ///
    /// - Parameters:
    ///   - blend: The list of weighted voice blends.
    ///   - phonemeCount: The total phoneme count used to slice the style pack.
    /// - Returns: The sliced style vector.
    /// - Throws: An error if loading the blend fails.
    public func styleVector(for blend: CastingProfile, phonemeCount: Int) throws -> StyleVector {
        let pack = try loadCastingProfile(blend)
        guard pack.shape.count == 2 else {
            throw StyleTTS2Error.expected2DVoicePack(blend.first?.voice ?? "", pack.shape)
        }
        let rows = pack.shape[0]
        let cols = pack.shape[1]

        let index = max(0, min(phonemeCount - 1, rows - 1))
        let startOffset = index * cols
        let rowData = Array(pack.data[startOffset..<(startOffset + cols)])

        return StyleVector(data: rowData, shape: [1, cols])
    }

    /// Convenience style vector resolver for a single voice name (or comma-separated blend string).
    ///
    /// - Parameters:
    ///   - voice: The voice name or comma-separated blend string.
    ///   - phonemeCount: The total phoneme count.
    /// - Returns: The sliced style vector.
    /// - Throws: An error if loading or parsing fails.
    public func styleVector(for voice: String, phonemeCount: Int) throws -> StyleVector {
        let parsedBlend = VoiceLoader.parseBlendString(voice)
        return try styleVector(for: parsedBlend, phonemeCount: phonemeCount)
    }

    /// Parses a comma-separated weight string like "anchor_female_adult:0.6,anchor_female_child:0.4".
    ///
    /// - Parameter input: The blend string.
    /// - Returns: An array of ``CastingProfile`` elements.
    public static func parseBlendString(_ input: String) -> CastingProfile {
        let parts = input.split(separator: ",").map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        return parts.compactMap { part in
            let voiceAndWeight = part.split(separator: ":").map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            guard !voiceAndWeight.isEmpty else { return nil }
            let name = String(voiceAndWeight[0])
            let weight = voiceAndWeight.count > 1 ? (Double(voiceAndWeight[1]) ?? 1.0) : 1.0
            return CastingProfile(voice: name, fraction: weight)
        }
    }

    /// Asynchronously loads a voice pack by name, downloading it if necessary and available.
    ///
    /// - Parameter voiceName: The name of the voice pack.
    /// - Returns: The loaded style vector.
    /// - Throws: An error if downloading or loading fails.
    public func loadVoiceAsync(named voiceName: String) async throws -> StyleVector {
        if let cached = cache.withLock({ $0.get(voiceName) }) {
            return cached
        }

        let safetensorsURL = baseDirectory.appendingPathComponent("\(voiceName).safetensors", isDirectory: false)
        let npyURL = baseDirectory.appendingPathComponent("\(voiceName).npy", isDirectory: false)

        if !FileManager.default.fileExists(atPath: safetensorsURL.path) &&
           !FileManager.default.fileExists(atPath: npyURL.path),
           let downloader = downloader {
            _ = try await downloader.downloadVoice(named: voiceName, toDirectory: baseDirectory)
        }

        return try loadVoice(named: voiceName)
    }

    /// Asynchronously creates a blended style array from multiple weighted voices.
    ///
    /// - Parameter blend: The list of weighted voice blends.
    /// - Returns: The combined style vector.
    /// - Throws: An error if loading fails.
    public func loadCastingProfileAsync(_ blend: CastingProfile) async throws -> StyleVector {
        precondition(!blend.isEmpty, "Voice blend list must not be empty.")
        if blend.count == 1, let single = blend.first {
            return try await loadVoiceAsync(named: single.voice)
        }

        var accumulator: [Float]?
        var totalFraction: Double = 0.0
        var shape: [Int] = []

        for target in blend {
            let pack = try await loadVoiceAsync(named: target.voice)
            if shape.isEmpty {
                shape = pack.shape
                accumulator = [Float](repeating: 0.0, count: pack.data.count)
            } else {
                precondition(pack.shape == shape, "Voice shapes in blend must match.")
            }
            
            let weight = Float(target.fraction)
            for i in 0..<pack.data.count {
                accumulator![i] += pack.data[i] * weight
            }
            totalFraction += target.fraction
        }

        guard let blended = accumulator, totalFraction > 0.0 else {
            throw StyleTTS2Error.missingVoice(blend.first?.voice ?? "(none)")
        }

        let finalFraction = Float(totalFraction)
        let normalized = blended.map { $0 / finalFraction }
        return StyleVector(data: normalized, shape: shape)
    }

    /// Asynchronously extracts the style embedding vector for a given phoneme count from a voice blend.
    ///
    /// - Parameters:
    ///   - blend: The list of weighted voice blends.
    ///   - phonemeCount: The total phoneme count.
    /// - Returns: The sliced style vector.
    /// - Throws: An error if loading fails.
    public func styleVectorAsync(for blend: CastingProfile, phonemeCount: Int) async throws -> StyleVector {
        let pack = try await loadCastingProfileAsync(blend)
        guard pack.shape.count == 2 else {
            throw StyleTTS2Error.expected2DVoicePack(blend.first?.voice ?? "", pack.shape)
        }
        let rows = pack.shape[0]
        let cols = pack.shape[1]

        let index = max(0, min(phonemeCount - 1, rows - 1))
        let startOffset = index * cols
        let rowData = Array(pack.data[startOffset..<(startOffset + cols)])

        return StyleVector(data: rowData, shape: [1, cols])
    }

    /// Asynchronous convenience style vector resolver for a single voice name (or comma-separated blend string).
    ///
    /// - Parameters:
    ///   - voice: The voice name or blend string.
    ///   - phonemeCount: The total phoneme count.
    /// - Returns: The sliced style vector.
    /// - Throws: An error if loading or parsing fails.
    public func styleVectorAsync(for voice: String, phonemeCount: Int) async throws -> StyleVector {
        let parsedBlend = VoiceLoader.parseBlendString(voice)
        return try await styleVectorAsync(for: parsedBlend, phonemeCount: phonemeCount)
    }

    /// Pure-Swift Safetensors file loader.
    ///
    /// - Parameter url: The URL of the `.safetensors` file to load.
    /// - Returns: A dictionary mapping tensor names to style vectors.
    /// - Throws: An error if parsing the header or reading data fails.
    public static func loadSafetensors(url: URL) throws -> [String: StyleVector] {
        let data = try Data(contentsOf: url, options: .mappedIfSafe)
        guard data.count >= 8 else {
            throw NSError(domain: "SafetensorsError", code: 1, userInfo: [NSLocalizedDescriptionKey: "File too small"])
        }
        let headerLen = data.withUnsafeBytes { $0.load(as: UInt64.self).littleEndian }
        let headerStart = 8
        let headerEnd = headerStart + Int(headerLen)
        guard data.count >= headerEnd else {
            throw NSError(domain: "SafetensorsError", code: 2, userInfo: [NSLocalizedDescriptionKey: "Invalid header length"])
        }
        
        let headerData = data.subdata(in: headerStart..<headerEnd)
        guard let json = try JSONSerialization.jsonObject(with: headerData) as? [String: Any] else {
            throw NSError(domain: "SafetensorsError", code: 3, userInfo: [NSLocalizedDescriptionKey: "Failed to parse JSON header"])
        }
        
        var result: [String: StyleVector] = [:]
        
        for (key, value) in json {
            if key == "__metadata__" { continue }
            guard let tensorDict = value as? [String: Any],
                  let dtype = tensorDict["dtype"] as? String,
                  let shape = tensorDict["shape"] as? [Int],
                  let offsets = tensorDict["data_offsets"] as? [Int],
                  offsets.count == 2 else {
                continue
            }
            
            let start = headerEnd + offsets[0]
            let end = headerEnd + offsets[1]
            guard data.count >= end else {
                throw NSError(domain: "SafetensorsError", code: 4, userInfo: [NSLocalizedDescriptionKey: "Data offsets out of bounds"])
            }
            
            let tensorData = data.subdata(in: start..<end)
            var floats: [Float] = []
            
            if dtype == "F32" {
                let count = tensorData.count / 4
                floats = [Float](repeating: 0, count: count)
                _ = floats.withUnsafeMutableBytes { destBytes in
                    tensorData.copyBytes(to: destBytes)
                }
            } else if dtype == "F16" {
                #if arch(arm64)
                let count = tensorData.count / 2
                var f16s = [Float16](repeating: 0, count: count)
                _ = f16s.withUnsafeMutableBytes { destBytes in
                    tensorData.copyBytes(to: destBytes)
                }
                floats = f16s.map { Float($0) }
                #else
                throw NSError(domain: "SafetensorsError", code: 5, userInfo: [NSLocalizedDescriptionKey: "Unsupported dtype Float16 on this architecture"])
                #endif
            } else {
                throw NSError(domain: "SafetensorsError", code: 6, userInfo: [NSLocalizedDescriptionKey: "Unsupported dtype: \(dtype)"])
            }
            
            result[key] = StyleVector(data: floats, shape: shape)
        }
        
        return result
    }
}

/// Represents a token's raw phonemes and its trailing whitespace.
public struct TokenPhonemes: Sendable {
    /// The phoneme string sequence.
    public let phonemes: String
    /// Trailing whitespace associated with this token.
    public let whitespace: String
    
    /// Initializes a new TokenPhonemes instance.
    ///
    /// - Parameters:
    ///   - phonemes: The phoneme string.
    ///   - whitespace: The trailing whitespace string.
    public init(phonemes: String, whitespace: String) {
        self.phonemes = phonemes
        self.whitespace = whitespace
    }
}

extension VoiceLoader {
    /// Asynchronously creates a 3D style matrix of shape [1, totalPhonemes, styleDim * 2]
    /// mapping each G2P token to its resolved voice blend embedding.
    ///
    /// - Parameters:
    ///   - tokens: The sequence of tokens with their phonemes.
    ///   - voiceBlends: The voice blends to apply per token.
    ///   - vocab: The vocabulary mapping string phonemes to integers.
    /// - Returns: The computed 3D style matrix style vector.
    /// - Throws: An error if voice loading or style extraction fails.
    public func styleMatrixAsync(
        for tokens: [TokenPhonemes],
        voiceBlends: [String],
        vocab: [String: Int]
    ) async throws -> StyleVector {
        precondition(!tokens.isEmpty, "Tokens must not be empty.")
        precondition(!voiceBlends.isEmpty, "Voice blends must not be empty.")
        
        // Match the whitespace trimming applied to the concatenated phonemes in the pipeline:
        // let chunkPhonemes = chunk.reduce(into: "") { ... }.trimmingCharacters(in: .whitespacesAndNewlines)
        var tokenStrings = tokens.map { $0.phonemes + $0.whitespace }
        let concat = tokenStrings.joined()
        
        // Trim leading whitespaces
        let leadingWhitespaceCount: Int = concat.prefix(while: { $0.isWhitespace }).count
        var tempLeading: Int = leadingWhitespaceCount
        for i in 0..<tokenStrings.count {
            if tempLeading <= 0 { break }
            let len = tokenStrings[i].count
            if tempLeading >= len {
                tokenStrings[i] = ""
                tempLeading -= len
            } else {
                let index = tokenStrings[i].index(tokenStrings[i].startIndex, offsetBy: tempLeading)
                tokenStrings[i] = String(tokenStrings[i][index...])
                tempLeading = 0
            }
        }
        
        // Trim trailing whitespaces
        let trailingWhitespaceCount: Int = concat.reversed().prefix(while: { $0.isWhitespace }).count
        var tempTrailing: Int = trailingWhitespaceCount
        for i in (0..<tokenStrings.count).reversed() {
            if tempTrailing <= 0 { break }
            let len = tokenStrings[i].count
            if tempTrailing >= len {
                tokenStrings[i] = ""
                tempTrailing -= len
            } else {
                let index = tokenStrings[i].index(tokenStrings[i].endIndex, offsetBy: -tempTrailing)
                tokenStrings[i] = String(tokenStrings[i][..<index])
                tempTrailing = 0
            }
        }
        
        // Calculate total phonemes in the sequence (including SOS and EOS) using trimmed token strings
        var totalPhonemes = 2
        for s in tokenStrings {
            let validPhonemeCount = s.compactMap { vocab[String($0)] }.count
            totalPhonemes += validPhonemeCount
        }

        var styleArrays: [StyleVector] = []
        
        // SOS token
        let firstBlend = VoiceLoader.parseBlendString(voiceBlends[0])
        let sosStyle = try await styleVectorAsync(for: firstBlend, phonemeCount: totalPhonemes)
        styleArrays.append(sosStyle)
        
        for (idx, _) in tokens.enumerated() {
            let blendIndex = min(idx, voiceBlends.count - 1)
            let blend = VoiceLoader.parseBlendString(voiceBlends[blendIndex])
            
            let s = tokenStrings[idx]
            let validPhonemeCount = s.compactMap { vocab[String($0)] }.count
            guard validPhonemeCount > 0 else { continue }
            
            let style = try await styleVectorAsync(for: blend, phonemeCount: totalPhonemes)
            
            var repeatedData: [Float] = []
            repeatedData.reserveCapacity(validPhonemeCount * style.data.count)
            for _ in 0..<validPhonemeCount {
                repeatedData.append(contentsOf: style.data)
            }
            let styleRepeated = StyleVector(data: repeatedData, shape: [validPhonemeCount, style.shape[1]])
            styleArrays.append(styleRepeated)
        }
        
        // EOS token
        let lastBlend = VoiceLoader.parseBlendString(voiceBlends.last!)
        let eosStyle = try await styleVectorAsync(for: lastBlend, phonemeCount: totalPhonemes)
        styleArrays.append(eosStyle)
        
        var concatenatedData: [Float] = []
        var totalRows = 0
        let cols = styleArrays.first?.shape[1] ?? 0
        for style in styleArrays {
            concatenatedData.append(contentsOf: style.data)
            totalRows += style.shape[0]
        }
        
        return StyleVector(data: concatenatedData, shape: [1, totalRows, cols])
    }
}

/// A simple thread-safe wrapper class that uses an NSLock to serialize access to an underlying value.
public final class Locked<T>: @unchecked Sendable {
    /// Lock used to serialize access to the value.
    private let lock = NSLock()
    /// The protected value.
    private var value: T

    /// Initializes the locked wrapper with an initial value.
    ///
    /// - Parameter value: The initial value to protect.
    public init(_ value: T) {
        self.value = value
    }

    /// Executes the given closure under lock, providing exclusive mutable access to the value.
    ///
    /// - Parameter action: The closure to execute.
    /// - Returns: The result of the closure.
    /// - Throws: Re-throws any error thrown by the action closure.
    public func withLock<R>(_ action: (inout T) throws -> R) rethrows -> R {
        lock.lock()
        defer { lock.unlock() }
        return try action(&value)
    }
}

// MARK: - LRUCache

/// A Least Recently Used (LRU) cache.
private final class LRUCache<Key: Hashable, Value>: @unchecked Sendable {
    private let limit: Int
    private var dict: [Key: Value] = [:]
    private var order: [Key] = []

    init(limit: Int) {
        self.limit = limit
    }

    func get(_ key: Key) -> Value? {
        guard let value = dict[key] else { return nil }
        if let idx = order.firstIndex(of: key) {
            order.remove(at: idx)
        }
        order.append(key)
        return value
    }

    func set(_ value: Value, forKey key: Key) {
        if dict[key] != nil {
            if let idx = order.firstIndex(of: key) {
                order.remove(at: idx)
            }
        }
        dict[key] = value
        order.append(key)

        while order.count > limit {
            let oldest = order.removeFirst()
            dict.removeValue(forKey: oldest)
        }
    }

    func removeAll() {
        dict.removeAll()
        order.orderReversedClean()
    }
}

private extension Array where Element: Equatable {
    mutating func orderReversedClean() {
        self.removeAll()
    }
}
