import Foundation
import Kit
import Stage

#if canImport(AppKit)
import AppKit
#endif

#if canImport(UIKit)
import UIKit
#endif

struct TuningFeedbackLogger {
    static var logFileURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // TuningFeedbackLogger.swift parent (ProsodiaTuner)
            .deletingLastPathComponent() // ProsodiaTuner
            .appendingPathComponent("TuningFeedback.md")
    }

    static func log(
        text: String,
        rating: Int,
        emotion: EmotionVector,
        speed: Double,
        volume: Double,
        voiceBlend: String,
        comment: String,
        spans: [ProsodySpan],
        mode: String,
        modelName: String?,
        globalConfig: ProsodiaConfig
    ) {
        let stars = String(repeating: "⭐", count: rating) + String(repeating: "☆", count: 5 - rating)
        
        let dateString = DateFormatter.localizedString(from: Date(), dateStyle: .short, timeStyle: .medium)
        
        let modelString = modelName.map { " (model: \($0))" } ?? ""
        var entry = """
        
        ### [\(dateString)] Rating: \(stars) (\(rating)/5)
        - **Mode**: \(mode)\(modelString)
        - **Passage**: "\(text)"
        - **Parameters**: Valence: \(String(format: "%.2f", emotion.valence)) | Arousal: \(String(format: "%.2f", emotion.arousal)) | Tension: \(String(format: "%.2f", emotion.tension))
        - **Modulation**: Speed ×\(String(format: "%.2f", speed)) | Volume ×\(String(format: "%.2f", volume))
        - **Voice Blend**: \(voiceBlend)
        - **Global Config**: Expressiveness: \(String(format: "%.2f", globalConfig.expressiveness)) | Speed Gains (A/T/V): \(String(format: "%.2f/%.2f/%.3f", globalConfig.speedArousalGain, globalConfig.speedTensionGain, globalConfig.speedValenceGain)) | Speed Limits: \(String(format: "%.2f...%.2f", globalConfig.speedMin, globalConfig.speedMax)) | Vol Gains (A/V): \(String(format: "%.2f/%.2f", globalConfig.gainArousalGain, globalConfig.gainValenceGain)) | Vol Limits: \(String(format: "%.2f...%.2f", globalConfig.gainMin, globalConfig.gainMax)) | Pauses (Sentence/Clause): \(String(format: "%.2fs/%.2fs", globalConfig.pauseSentence, globalConfig.pauseClause)) | Blend (Sigma/Min/Proximity): \(String(format: "%.2f/%.2f/%.2f", globalConfig.blendSigma, globalConfig.blendMinimumFraction, globalConfig.blendProximityThreshold))
        """
        
        if !comment.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            entry += "\n- **Subjective Feedback**: \(comment)"
        }
        
        if spans.count > 1 {
            entry += "\n- **Parsed Phrases (Spans)**:"
            for (i, span) in spans.enumerated() {
                var pauseText = ""
                if span.leadingPause > 0 {
                    pauseText = String(format: " (pause: %.2fs)", span.leadingPause)
                }
                entry += "\n  - Phrase \(i+1): \"\(span.text)\"\(pauseText) | speed ×\(String(format: "%.2f", span.speed)) | vol \(Int((span.gain * 100).rounded()))%"
            }
        }
        entry += "\n\n---"
        
        // Write to file on disk
        do {
            if !FileManager.default.fileExists(atPath: logFileURL.path) {
                let header = """
                # Prosody Audition Feedback Log
                
                This log is automatically generated by the audition harness to capture subjective reviews and knobs tuning. Share these logs in chat so the AI assistant can tune prompts, AcousticMatrix, sigmas, and voice anchors.
                
                ---
                """
                try header.write(to: logFileURL, atomically: true, encoding: .utf8)
            }
            
            if let fileHandle = try? FileHandle(forWritingTo: logFileURL) {
                defer { fileHandle.closeFile() }
                fileHandle.seekToEndOfFile()
                if let data = entry.data(using: .utf8) {
                    fileHandle.write(data)
                }
            }
        } catch {
            print("Failed to write tuning feedback to disk: \(error.localizedDescription)")
        }
        
        // Copy to system clipboard
        #if canImport(AppKit)
        let pasteboard = NSPasteboard.general
        pasteboard.declareTypes([.string], owner: nil)
        pasteboard.setString(entry, forType: .string)
        #elseif canImport(UIKit)
        UIPasteboard.general.string = entry
        #endif
    }
}
