// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_AUDIO_SINK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_AUDIO_SINK_METHOD0
typedef void (*UniffiCallbackInterfaceAudioSinkMethod0)(uint64_t, RustBuffer, uint32_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER_METHOD0
typedef void (*UniffiCallbackInterfaceModelAssetManagerMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER_METHOD1
typedef void (*UniffiCallbackInterfaceModelAssetManagerMethod1)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROSODIA_G2P_PROCESSOR_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROSODIA_G2P_PROCESSOR_METHOD0
typedef void (*UniffiCallbackInterfaceProsodiaG2pProcessorMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROSODIA_SPEECH_ENGINE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROSODIA_SPEECH_ENGINE_METHOD0
typedef void (*UniffiCallbackInterfaceProsodiaSpeechEngineMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_VOICE_ASSET_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_VOICE_ASSET_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceVoiceAssetProviderMethod0)(uint64_t, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_AUDIO_SINK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_AUDIO_SINK
typedef struct UniffiVTableCallbackInterfaceAudioSink {
    UniffiCallbackInterfaceAudioSinkMethod0 _Nonnull scheduleAudio;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceAudioSink;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_MODEL_ASSET_MANAGER
typedef struct UniffiVTableCallbackInterfaceModelAssetManager {
    UniffiCallbackInterfaceModelAssetManagerMethod0 _Nonnull loadStyleAnchor;
    UniffiCallbackInterfaceModelAssetManagerMethod1 _Nonnull resolveCastingProfile;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceModelAssetManager;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROSODIA_G2P_PROCESSOR
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROSODIA_G2P_PROCESSOR
typedef struct UniffiVTableCallbackInterfaceProsodiaG2pProcessor {
    UniffiCallbackInterfaceProsodiaG2pProcessorMethod0 _Nonnull process;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceProsodiaG2pProcessor;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROSODIA_SPEECH_ENGINE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROSODIA_SPEECH_ENGINE
typedef struct UniffiVTableCallbackInterfaceProsodiaSpeechEngine {
    UniffiCallbackInterfaceProsodiaSpeechEngineMethod0 _Nonnull synthesize;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceProsodiaSpeechEngine;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_VOICE_ASSET_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_VOICE_ASSET_PROVIDER
typedef struct UniffiVTableCallbackInterfaceVoiceAssetProvider {
    UniffiCallbackInterfaceVoiceAssetProviderMethod0 _Nonnull loadVoiceBytes;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceVoiceAssetProvider;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_BASICG2PPROCESSOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_BASICG2PPROCESSOR
void*_Nonnull uniffi_actor_fn_clone_basicg2pprocessor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_BASICG2PPROCESSOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_BASICG2PPROCESSOR
void uniffi_actor_fn_free_basicg2pprocessor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_BASICG2PPROCESSOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_BASICG2PPROCESSOR_NEW
void*_Nonnull uniffi_actor_fn_constructor_basicg2pprocessor_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_BASICG2PPROCESSOR_PROCESS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_BASICG2PPROCESSOR_PROCESS
RustBuffer uniffi_actor_fn_method_basicg2pprocessor_process(void*_Nonnull ptr, RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_DEFAULTMODELASSETMANAGER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_DEFAULTMODELASSETMANAGER
void*_Nonnull uniffi_actor_fn_clone_defaultmodelassetmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_DEFAULTMODELASSETMANAGER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_DEFAULTMODELASSETMANAGER
void uniffi_actor_fn_free_defaultmodelassetmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_DEFAULTMODELASSETMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_DEFAULTMODELASSETMANAGER_NEW
void*_Nonnull uniffi_actor_fn_constructor_defaultmodelassetmanager_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_DEFAULTMODELASSETMANAGER_LOAD_STYLE_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_DEFAULTMODELASSETMANAGER_LOAD_STYLE_ANCHOR
RustBuffer uniffi_actor_fn_method_defaultmodelassetmanager_load_style_anchor(void*_Nonnull ptr, RustBuffer _voice_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_DEFAULTMODELASSETMANAGER_RESOLVE_CASTING_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_DEFAULTMODELASSETMANAGER_RESOLVE_CASTING_PROFILE
RustBuffer uniffi_actor_fn_method_defaultmodelassetmanager_resolve_casting_profile(void*_Nonnull ptr, RustBuffer profile, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_PROSODIAACTORENGINE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_PROSODIAACTORENGINE
void*_Nonnull uniffi_actor_fn_clone_prosodiaactorengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_PROSODIAACTORENGINE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_PROSODIAACTORENGINE
void uniffi_actor_fn_free_prosodiaactorengine(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_PROSODIAACTORENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_PROSODIAACTORENGINE_NEW
void*_Nonnull uniffi_actor_fn_constructor_prosodiaactorengine_new(void*_Nonnull pipeline, uint64_t speech_engine, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_PROSODIAACTORENGINE_PROCESS_AND_SYNTHESIZE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_PROSODIAACTORENGINE_PROCESS_AND_SYNTHESIZE
RustBuffer uniffi_actor_fn_method_prosodiaactorengine_process_and_synthesize(void*_Nonnull ptr, RustBuffer span, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_PROSODIAACTORPIPELINE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_PROSODIAACTORPIPELINE
void*_Nonnull uniffi_actor_fn_clone_prosodiaactorpipeline(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_PROSODIAACTORPIPELINE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_PROSODIAACTORPIPELINE
void uniffi_actor_fn_free_prosodiaactorpipeline(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_PROSODIAACTORPIPELINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_PROSODIAACTORPIPELINE_NEW
void*_Nonnull uniffi_actor_fn_constructor_prosodiaactorpipeline_new(uint64_t g2p, uint64_t asset_manager, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_PROSODIAACTORPIPELINE_PROCESS_SPAN
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_PROSODIAACTORPIPELINE_PROCESS_SPAN
RustBuffer uniffi_actor_fn_method_prosodiaactorpipeline_process_span(void*_Nonnull ptr, RustBuffer span, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_VOICELOADER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CLONE_VOICELOADER
void*_Nonnull uniffi_actor_fn_clone_voiceloader(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_VOICELOADER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FREE_VOICELOADER
void uniffi_actor_fn_free_voiceloader(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_VOICELOADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_CONSTRUCTOR_VOICELOADER_NEW
void*_Nonnull uniffi_actor_fn_constructor_voiceloader_new(uint64_t provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_CLEAR_CACHE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_CLEAR_CACHE
void uniffi_actor_fn_method_voiceloader_clear_cache(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_LOAD_BLEND
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_LOAD_BLEND
RustBuffer uniffi_actor_fn_method_voiceloader_load_blend(void*_Nonnull ptr, RustBuffer blend, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_LOAD_VOICE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_LOAD_VOICE
RustBuffer uniffi_actor_fn_method_voiceloader_load_voice(void*_Nonnull ptr, RustBuffer voice_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_STYLE_MATRIX
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_STYLE_MATRIX
RustBuffer uniffi_actor_fn_method_voiceloader_style_matrix(void*_Nonnull ptr, RustBuffer tokens, RustBuffer voice_blends, RustBuffer vocab, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_STYLE_VECTOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_METHOD_VOICELOADER_STYLE_VECTOR
RustBuffer uniffi_actor_fn_method_voiceloader_style_vector(void*_Nonnull ptr, RustBuffer voice, int64_t phoneme_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_AUDIOSINK
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_AUDIOSINK
void uniffi_actor_fn_init_callback_vtable_audiosink(UniffiVTableCallbackInterfaceAudioSink* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_MODELASSETMANAGER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_MODELASSETMANAGER
void uniffi_actor_fn_init_callback_vtable_modelassetmanager(UniffiVTableCallbackInterfaceModelAssetManager* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_PROSODIAG2PPROCESSOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_PROSODIAG2PPROCESSOR
void uniffi_actor_fn_init_callback_vtable_prosodiag2pprocessor(UniffiVTableCallbackInterfaceProsodiaG2pProcessor* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_PROSODIASPEECHENGINE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_PROSODIASPEECHENGINE
void uniffi_actor_fn_init_callback_vtable_prosodiaspeechengine(UniffiVTableCallbackInterfaceProsodiaSpeechEngine* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_VOICEASSETPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_INIT_CALLBACK_VTABLE_VOICEASSETPROVIDER
void uniffi_actor_fn_init_callback_vtable_voiceassetprovider(UniffiVTableCallbackInterfaceVoiceAssetProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_BLEND_STYLE_PACKS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_BLEND_STYLE_PACKS
RustBuffer uniffi_actor_fn_func_blend_style_packs(RustBuffer packs, RustBuffer fractions, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_CHUNK_PHONEMES
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_CHUNK_PHONEMES
RustBuffer uniffi_actor_fn_func_chunk_phonemes(RustBuffer phonemes, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_CHUNK_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_CHUNK_TOKENS
RustBuffer uniffi_actor_fn_func_chunk_tokens(RustBuffer tokens, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_NORMALIZE_STYLE_PACK
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_NORMALIZE_STYLE_PACK
RustBuffer uniffi_actor_fn_func_normalize_style_pack(RustBuffer pack, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_PARSE_BLEND_STRING
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_PARSE_BLEND_STRING
RustBuffer uniffi_actor_fn_func_parse_blend_string(RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_PARSE_SAFETENSORS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_PARSE_SAFETENSORS
RustBuffer uniffi_actor_fn_func_parse_safetensors(RustBuffer bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_SLICE_STYLE_ROW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_FN_FUNC_SLICE_STYLE_ROW
RustBuffer uniffi_actor_fn_func_slice_style_row(RustBuffer pack, int64_t phoneme_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_ALLOC
RustBuffer ffi_actor_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_actor_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_FREE
void ffi_actor_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ACTOR_RUSTBUFFER_RESERVE
RustBuffer ffi_actor_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U8
void ffi_actor_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U8
void ffi_actor_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U8
void ffi_actor_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_actor_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I8
void ffi_actor_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I8
void ffi_actor_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I8
void ffi_actor_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I8
int8_t ffi_actor_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U16
void ffi_actor_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U16
void ffi_actor_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U16
void ffi_actor_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_actor_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I16
void ffi_actor_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I16
void ffi_actor_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I16
void ffi_actor_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I16
int16_t ffi_actor_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U32
void ffi_actor_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U32
void ffi_actor_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U32
void ffi_actor_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_actor_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I32
void ffi_actor_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I32
void ffi_actor_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I32
void ffi_actor_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I32
int32_t ffi_actor_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_U64
void ffi_actor_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_U64
void ffi_actor_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_U64
void ffi_actor_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_actor_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_I64
void ffi_actor_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_I64
void ffi_actor_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_I64
void ffi_actor_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_I64
int64_t ffi_actor_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_F32
void ffi_actor_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_F32
void ffi_actor_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_F32
void ffi_actor_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_F32
float ffi_actor_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_F64
void ffi_actor_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_F64
void ffi_actor_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_F64
void ffi_actor_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_F64
double ffi_actor_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_POINTER
void ffi_actor_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_POINTER
void ffi_actor_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_POINTER
void ffi_actor_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_actor_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_actor_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_actor_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_actor_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_actor_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_POLL_VOID
void ffi_actor_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_CANCEL_VOID
void ffi_actor_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_FREE_VOID
void ffi_actor_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ACTOR_RUST_FUTURE_COMPLETE_VOID
void ffi_actor_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_BLEND_STYLE_PACKS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_BLEND_STYLE_PACKS
uint16_t uniffi_actor_checksum_func_blend_style_packs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_CHUNK_PHONEMES
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_CHUNK_PHONEMES
uint16_t uniffi_actor_checksum_func_chunk_phonemes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_CHUNK_TOKENS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_CHUNK_TOKENS
uint16_t uniffi_actor_checksum_func_chunk_tokens(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_NORMALIZE_STYLE_PACK
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_NORMALIZE_STYLE_PACK
uint16_t uniffi_actor_checksum_func_normalize_style_pack(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_PARSE_BLEND_STRING
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_PARSE_BLEND_STRING
uint16_t uniffi_actor_checksum_func_parse_blend_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_PARSE_SAFETENSORS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_PARSE_SAFETENSORS
uint16_t uniffi_actor_checksum_func_parse_safetensors(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_SLICE_STYLE_ROW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_FUNC_SLICE_STYLE_ROW
uint16_t uniffi_actor_checksum_func_slice_style_row(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_BASICG2PPROCESSOR_PROCESS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_BASICG2PPROCESSOR_PROCESS
uint16_t uniffi_actor_checksum_method_basicg2pprocessor_process(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_DEFAULTMODELASSETMANAGER_LOAD_STYLE_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_DEFAULTMODELASSETMANAGER_LOAD_STYLE_ANCHOR
uint16_t uniffi_actor_checksum_method_defaultmodelassetmanager_load_style_anchor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_DEFAULTMODELASSETMANAGER_RESOLVE_CASTING_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_DEFAULTMODELASSETMANAGER_RESOLVE_CASTING_PROFILE
uint16_t uniffi_actor_checksum_method_defaultmodelassetmanager_resolve_casting_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAACTORENGINE_PROCESS_AND_SYNTHESIZE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAACTORENGINE_PROCESS_AND_SYNTHESIZE
uint16_t uniffi_actor_checksum_method_prosodiaactorengine_process_and_synthesize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAACTORPIPELINE_PROCESS_SPAN
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAACTORPIPELINE_PROCESS_SPAN
uint16_t uniffi_actor_checksum_method_prosodiaactorpipeline_process_span(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_CLEAR_CACHE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_CLEAR_CACHE
uint16_t uniffi_actor_checksum_method_voiceloader_clear_cache(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_LOAD_BLEND
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_LOAD_BLEND
uint16_t uniffi_actor_checksum_method_voiceloader_load_blend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_LOAD_VOICE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_LOAD_VOICE
uint16_t uniffi_actor_checksum_method_voiceloader_load_voice(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_STYLE_MATRIX
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_STYLE_MATRIX
uint16_t uniffi_actor_checksum_method_voiceloader_style_matrix(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_STYLE_VECTOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICELOADER_STYLE_VECTOR
uint16_t uniffi_actor_checksum_method_voiceloader_style_vector(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_BASICG2PPROCESSOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_BASICG2PPROCESSOR_NEW
uint16_t uniffi_actor_checksum_constructor_basicg2pprocessor_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_DEFAULTMODELASSETMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_DEFAULTMODELASSETMANAGER_NEW
uint16_t uniffi_actor_checksum_constructor_defaultmodelassetmanager_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_PROSODIAACTORENGINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_PROSODIAACTORENGINE_NEW
uint16_t uniffi_actor_checksum_constructor_prosodiaactorengine_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_PROSODIAACTORPIPELINE_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_PROSODIAACTORPIPELINE_NEW
uint16_t uniffi_actor_checksum_constructor_prosodiaactorpipeline_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_VOICELOADER_NEW
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_CONSTRUCTOR_VOICELOADER_NEW
uint16_t uniffi_actor_checksum_constructor_voiceloader_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_AUDIOSINK_SCHEDULE_AUDIO
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_AUDIOSINK_SCHEDULE_AUDIO
uint16_t uniffi_actor_checksum_method_audiosink_schedule_audio(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_MODELASSETMANAGER_LOAD_STYLE_ANCHOR
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_MODELASSETMANAGER_LOAD_STYLE_ANCHOR
uint16_t uniffi_actor_checksum_method_modelassetmanager_load_style_anchor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_MODELASSETMANAGER_RESOLVE_CASTING_PROFILE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_MODELASSETMANAGER_RESOLVE_CASTING_PROFILE
uint16_t uniffi_actor_checksum_method_modelassetmanager_resolve_casting_profile(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAG2PPROCESSOR_PROCESS
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIAG2PPROCESSOR_PROCESS
uint16_t uniffi_actor_checksum_method_prosodiag2pprocessor_process(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIASPEECHENGINE_SYNTHESIZE
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_PROSODIASPEECHENGINE_SYNTHESIZE
uint16_t uniffi_actor_checksum_method_prosodiaspeechengine_synthesize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICEASSETPROVIDER_LOAD_VOICE_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ACTOR_CHECKSUM_METHOD_VOICEASSETPROVIDER_LOAD_VOICE_BYTES
uint16_t uniffi_actor_checksum_method_voiceassetprovider_load_voice_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ACTOR_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ACTOR_UNIFFI_CONTRACT_VERSION
uint32_t ffi_actor_uniffi_contract_version(void
    
);
#endif

